### PR TITLE
Custom value transforms

### PR DESCRIPTION
**Pull request by dzegarra**
I'm working on a project where a huge JSON with a key-value structure where all the data are strings.
A form is created dynamically based on this JSON structure and based on pre-defined rules, some of these properties are presented as text fields, text fields that allow numbers only, and others as checkboxes.

The form data then needs to be sent back to the backend in the same format as it was received, with all its values as strings.

react-hook-form documentation includes [an example](https://www.react-hook-form.com/advanced-usage/#TransformandParse) to transform the values back and forward between the form data and the UI component but the current implementation of CheckBoxElement and TextFieldElement does not allow making these changes.

That's why I'm creating this PR.

> I closed my previous PR with the same title because I forgot to change the email address of my commits 😅.

### CODE REVIEW

**Comment by dohomi** [comment]
@dzegarra your PR looks good could you resolve the conflicts that I can proceed with the merge?

**Comment by sadik-malik** [comment]
> The form data then needs to be sent back to the backend in the same format as it was received, with all its values as strings.

This PR seems interesting considering the above use case, @dohomi we can create useControllerPlus hook and replace useController with it across all the components to support the transform prop.

**Comment by dohomi** [comment]
this PR has currently conflicts which needs to be resolved first

**Comment by dohomi** [comment]
this has been implemented in another way

**Pull request closed without merging**
