### PR TITLE
fix ci errors

### PR DESCRIPTION
**Pull request by MaskedHawk**
Copy code
Hello,

just a small pull request where I removed some parts from various TypeScript interfaces. 
The CI seems to be working fine now. Additionally, I had to add `simple-git-hooks` inside the `rhf-mui/package.json` file because of your `prepare` script. 

I hope this helps!

### CODE REVIEW

**Comment by dohomi** [comment]
@MaskedHawk the TypeScript changes you suggested will have any drawback of creating type safe controls?

**Comment by MaskedHawk** [comment]
@dohomi, you're right. It was indeed the quickest solution.
After further exploration of the React Hook Form's code, I realized that the ControllerProps requires a generic type to be specified.
I've now updated my pull request to accommodate this change.

**Comment by dohomi** [comment]
@MaskedHawk thanks release is out with you changes!

**Comment by MaskedHawk** [comment]
thanks hope you'll release soon

**Comment by dohomi** [comment]
> @MaskedHawk thanks release is out with you changes!

the release is out

**Pull request merged**
