### PR TITLE
Custom value transform for all components

### PR DESCRIPTION
**Pull request by sadik-malik**
This PR enables all components to accept the "transform" prop and introduces breaking changes. I've attempted to maintain the same API for most components, but please note that alterations to component value types in this PR may result in type errors for some users.

Breaking Changes:

- The transform.output prop in TextFieldElement now passes the event object to the callback instead of event.target.value or +event.target.value.
- The types of value and options props have changed for some components. Consequently, some users may encounter type errors in their code.

@dohomi, if we can merge this in v7 branch and release this as a canary version for the package. I believe, that would be better. This way, more users can test this and provide their feedback to the changes in this PR.

### CODE REVIEW

**Comment by SamLeatherdale** [comment]
Thanks for adding this @sadik-malik, I was going to raise a PR myself to add it specifically to the Autocomplete component to better support creating new items in a `freeSolo` Autocomplete. 

Currently I'm letting it add a new string into the values and then using `setValue` to change the string into an option object, but with the transform I'll be able to always ensure an option object is set 🎉

**Comment by dohomi** [comment]
@sadik-malik thank you for your efforts. Your current PR is only possible to be merged into the master branch (as you created it from there I think). Is that OK for you? I can still release it as v7-beta and if everything is OK we push the release further

**Comment by sadik-malik** [comment]
Ok, we can release it as v7-beta. Also, I will updating the storybook example for this new prop as well in my free time.

**Comment by sadik-malik** [comment]
Changed branch to v7

**Comment by dohomi** [comment]
I released  7.0.0-beta.0 to npm

**Pull request merged**
