### PR TITLE
Convert `.tsx` stories to `.mdx`

### PR DESCRIPTION
**Pull request by ChromeGG**
Todo:

- [ ] Fix TS support in `.mdx` stories,
- [ ] Port rest of stories

### CODE REVIEW

**Comment by dohomi** [comment]
looking forward thanks for your work on this!

**Comment by TkaczykAdam** [comment]
Dammit, I made some small research. Seems that TS is not supported in `.mdx` and storybook:
https://github.com/microsoft/TypeScript/issues/36440

**Review by netknight — CHANGES_REQUESTED** [review]
Is there any update?

**Comment by dohomi** [comment]
@netknight I haven't digged further into this PR as `.tsx` was working fine for now. if you have experience in it please go ahead I am happy to review

**Comment by dohomi** [comment]
I migrated to vite and storybook v7. will close this PR for now as it is definitely outdated.

**Pull request closed without merging**
