### PR TITLE
Element should have a focus ref

### PR DESCRIPTION
**Pull request by RubtsovAV**
These changes add the ability to use `setFocus` on field forms. For example, when you want to set focus on an element after mount: 
```
import React from "react";
import { useForm } from "react-hook-form";
import { FormContainer, TextFieldElement } from "react-hook-form-mui";

export default function ExampleForm() {
  const form = useForm({
    defaultValues: {
      login: "",
    },
  });

  React.useEffect(() => {
    setTimeout(() => {
      form.setFocus("login");
    }, 1);
  }, [form]);

  return (
    <FormContainer formContext={form}>
      <TextFieldElement name="login" label="Login" required fullWidth />
    </FormContainer>
  );
}
```
This also resolves the issue https://github.com/dohomi/react-hook-form-mui/issues/102

### CODE REVIEW

**Comment by RubtsovAV** [comment]
The prettier automatically applied code style format from .prettierrc config. Let me know if you want to change it.

**Comment by dohomi** [comment]
@RubtsovAV I updated the package just now and included a yarn lint script in the root of the package. Could you please run this over your PR that its more readable what changes you have made? Thanks

**Comment by RubtsovAV** [comment]
@dohomi Done.

**Comment by dohomi** [comment]
Thanks @RubtsovAV !

**Comment by RubtsovAV** [comment]
@dohomi BTW. I guess would be useful to add these, because the prettier always try to apply a code style.

```
    "prettier": "npx prettier apps/nextjs/src/** packages/rhf-mui/src/** apps/storybook/stories/** apps/storybook/src/** --check",
    "prettier:fix": "npm run prettier -- --write",
```

**Comment by dohomi** [comment]
@RubtsovAV I thought the prettier-plugin inside of eslint takes care of these?

**Comment by RubtsovAV** [comment]
@dohomi It gives a different result.

**Comment by dohomi** [comment]
i merged it into the latest release 👍

**Comment by dohomi** [comment]
@RubtsovAV could you elaborate why the focusRef is breaking for some users as in #113

**Comment by RubtsovAV** [comment]
> @RubtsovAV could you elaborate why the focusRef is breaking for some users as in #113 

Here is the fix https://github.com/dohomi/react-hook-form-mui/pull/121

P.S. I guess I know why I didn't catch this issue in the storybook. Because it appears there in front of the input and looked fine. Sorry for this.

**Pull request merged**
